config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  # get 'home/index'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # about us page here
  get 'home/about'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/workout.rb
class Workout < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[ show edit update destroy ]

  # GET /workouts or /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1 or /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts or /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully created." }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1 or /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully updated." }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1 or /workouts/1.json
  def destroy
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url, notice: "Workout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:name, :description, :dificulty, :reps, :sets, :focus)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "FitAddict", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "View workouts", workouts_path, class:"nav-link active" %>
          
        </li>


         <li class="nav-item">
         <%= link_to "create workouts", new_workout_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h2> This here is out about us page </h2>

<button type="button" class="btn btn-primary"> Click me </button>

app/views/home/index.html.erb
<h1> Home page. Welcome on board </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
 
     <title>FitAddict</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    
  <%= render 'home/navbar' %>
  <div class="container">   <%= yield %> </div>
    <footer> Developed by lekan @2022. check <a href="https://lekan.dev"> lekan.dev </a> </footer>

    # Optional JavaScript; choose one of the two! 

    # Option 1: Bootstrap Bundle with Popper 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    # Option 2: Separate Popper and Bootstrap JS 
   
    # <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    # <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    # 
  </body>
</html>

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
  <% if workout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :dificulty, style: "display: block" %>
    <%= form.text_field :dificulty %>
  </div>

  <div>
    <%= form.label :reps, style: "display: block" %>
    <%= form.number_field :reps %>
  </div>

  <div>
    <%= form.label :sets, style: "display: block" %>
    <%= form.number_field :sets %>
  </div>

  <div>
    <%= form.label :focus, style: "display: block" %>
    <%= form.text_field :focus %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <p>
    <strong>Name:</strong>
    <%= workout.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= workout.description %>
  </p>

  <p>
    <strong>Dificulty:</strong>
    <%= workout.dificulty %>
  </p>

  <p>
    <strong>Reps:</strong>
    <%= workout.reps %>
  </p>

  <p>
    <strong>Sets:</strong>
    <%= workout.sets %>
  </p>

  <p>
    <strong>Focus:</strong>
    <%= workout.focus %>
  </p>

</div>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Show this workout", @workout %> |
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workouts</h1>

<div id="workouts">
  <% @workouts.each do |workout| %>
    <%= render workout %>
    <p>
      <%= link_to "Show this workout", workout %>
    </p>
  <% end %>
</div>

<%= link_to "New workout", new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workout %>

<div>
  <%= link_to "Edit this workout", edit_workout_path(@workout) %> |
  <%= link_to "Back to workouts", workouts_path %>

  <%= button_to "Destroy this workout", @workout, method: :delete %>
</div>